language: python
sudo: required
matrix:
  include:
#  - os: windows
#    python: '2.7'
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
  - os: linux
    dist: trusty
    python: '3.5'
  - os: linux
    dist: trusty
    python: '3.6'
  - os: linux
    dist: xenial
    python: '3.7'
  - os: linux
    dist: xenial
    python: '3.8'
  - os: linux
    sudo: false
    python: pypy
  - os: linux
    sudo: false
    python: pypy3
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.5
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.6.5
install:
- pip install coveralls
- pip install tox-travis
script:
- tox
after_success:
- coveralls
- bash <(curl -s https://codecov.io/bash)
